---
- name: Install required packages
  hosts: minion
  become: true  # Run tasks with elevated privileges

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache2, MariaDB, syslog-ng, net-tools, Python3, and python3-pymysql
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mariadb-server
        - syslog-ng
        - net-tools
        - python3
        - python3-pymysql

    - name: Ensure services are started and enabled
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mariadb
        - syslog-ng
